import { createI18n } from 'vue-i18n'
import { countriesFr, countriesEn } from './countries'

export const SUPPORTED_LOCALES = ['fr', 'en'] as const
export type Locale = (typeof SUPPORTED_LOCALES)[number]

const STORAGE_KEY = 'tl_locale'

function detectLocale(): Locale {
  const stored = localStorage.getItem(STORAGE_KEY)
  if (stored === 'fr' || stored === 'en') return stored
  const browser = navigator.language?.slice(0, 2).toLowerCase()
  return browser === 'en' ? 'en' : 'fr'
}

const messages = {
  fr: {
    login: {
      kicker: '// CONNEXION — CONSOLE',
      title: 'Bienvenue sur Threatlab.',
      lead: 'Connectez-vous à votre console de supervision des honeypots.',
      username: 'Username',
      password: 'Mot de passe',
      submit: 'Se connecter',
      info1: 'Accès réservé. Toute connexion est journalisée et corrélée.',
      info2: 'Identifiants oubliés ? Contactez votre administrateur.',
    },
    a2f: {
      kicker: '// VÉRIFICATION EN DEUX ÉTAPES',
      title: 'Confirmez votre identité.',
      lead: 'Saisissez le code à 6 chiffres généré par votre application d’authentification.',
      info1: 'Accès réservé. Toute connexion est journalisée et corrélée.',
      info2: 'Vous n’avez plus accès à votre application ? Contactez votre administrateur.',
      invalidCode: 'Code de vérification invalide',
    },
    errors: {
      invalidCredentials: 'Nom d’utilisateur ou mot de passe incorrect.',
      notAuthenticated: 'Session expirée. Veuillez vous reconnecter.',
      emptyCode: 'Veuillez entrer un code de vérification.',
      invalidCode: 'Code de vérification invalide.',
      generic: 'Connexion impossible. Réessayez plus tard.',
    },
    side: {
      title: 'Votre plateforme de threat intelligence, auto-hébergée.',
      leadPre: 'Déployez des honeypots, collectez les attaques et ',
      leadEm: 'analysez les menaces',
      leadPost: ', le tout sur votre propre infrastructure.',
      stat1: 'AUTO-HÉBERGÉ',
      stat2: 'PROTOCOLES ÉMULÉS',
      stat3: 'TÉLÉMÉTRIE EXTERNE',
      stat4: 'ANALYSE TEMPS RÉEL',
      foot: '© 2026 Threatlab · Plateforme de threat intelligence',
    },
    countries: countriesFr,
  },
  en: {
    login: {
      kicker: '// SIGN IN — CONSOLE',
      title: 'Welcome to Threatlab.',
      lead: 'Sign in to your honeypot monitoring console.',
      username: 'Username',
      password: 'Password',
      submit: 'Sign in',
      info1: 'Restricted access. Every login is logged and correlated.',
      info2: 'Forgot your credentials? Contact your administrator.',
    },
    a2f: {
      kicker: '// TWO-FACTOR AUTHENTICATION',
      title: 'Confirm your identity.',
      lead: 'Enter the 6-digit code generated by your authenticator app.',
      info1: 'Restricted access. Every login is logged and correlated.',
      info2: 'Lost access to your authenticator app? Contact your administrator.',
      invalidCode: 'Invalid verification code',
    },
    errors: {
      invalidCredentials: 'Invalid username or password.',
      notAuthenticated: 'Session expired. Please sign in again.',
      emptyCode: 'Please enter a verification code.',
      invalidCode: 'Invalid verification code.',
      generic: 'Unable to sign in. Please try again later.',
    },
    side: {
      title: 'Your self-hosted threat intelligence platform.',
      leadPre: 'Deploy honeypots, collect attacks and ',
      leadEm: 'analyze threats',
      leadPost: ', all on your own infrastructure.',
      stat1: 'SELF-HOSTED',
      stat2: 'EMULATED PROTOCOLS',
      stat3: 'EXTERNAL TELEMETRY',
      stat4: 'REAL-TIME ANALYSIS',
      foot: '© 2026 Threatlab · Threat intelligence platform',
    },
    countries: countriesEn,
  },
}

const i18n = createI18n({
  legacy: false,
  globalInjection: true,
  locale: detectLocale(),
  fallbackLocale: 'fr',
  messages,
})

const AUTH_ERROR_KEYS: Record<string, string> = {
  'Invalid username or password': 'errors.invalidCredentials',
  'Non authentifié': 'errors.notAuthenticated',
  'Veuillez entrer un code de vérification': 'errors.emptyCode',
  'Code de vérification invalide': 'errors.invalidCode',
  'Erreur de connexion': 'errors.generic',
  'Erreur de vérification': 'errors.generic',
}

export function authErrorKey(raw: string | null | undefined): string | null {
  if (!raw) return null
  return AUTH_ERROR_KEYS[raw.trim()] ?? null
}

export function setLocale(locale: Locale) {
  i18n.global.locale.value = locale
  localStorage.setItem(STORAGE_KEY, locale)
  document.documentElement.setAttribute('lang', locale)
}

document.documentElement.setAttribute('lang', i18n.global.locale.value)

export default i18n
